server:
  session-timeout: 1800
  port: 8080
  host: 124.128.14.206
  servlet:
    context-path: /cloudTransfer
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: pro
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true

#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: redis

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    cacheEnabled: true
  mapper-locations: mapper/**/*Mapper.xml
  typeAliasesPackage: com.hema.newretail.**.domain

#tcp端口
#不能用localhost,否则启动报异常:Unresolved address
#tcp监听的端口
tcp:
  port: 2007
  host: 192.168.2.110
# bossGroup的线程数
boss:
  thread:
    count: 2
# worker的线程数
worker:
  thread:
    count: 2
#是否使用长连接
so:
  keepalive:  true
  backlog: 100
